### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by hanserasmus** [Olen/kea_hooks#1]
Hi 

I have tried compiling this software from source. But I am running into errors, which does not clearly state what is wrong.

Environment: CentOS 7.2
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-16)

The only errors I have to go by is the following:
`pkt4_send.cc:41:52: error: no matching function for call to 'regex_replace(std::string&, std::regex&, const char [2])'
  hwaddr_windows = regex_replace (hwaddr, colon, "-");
`
and 
`pkt4_send.cc: In function 'std::string get4Option(isc::dhcp::Pkt4Ptr&, uint8_t, uint8_t, bool)':
pkt4_send.cc:322:58: error: no matching function for call to 'regex_replace(std::string&, std::regex&, const char [2])'
   option_data = regex_replace (option_data, sanitize, "_");
                                                                                          ^`
and it ends with:

`make[1]: *** [libduc_la-pkt4_send.lo] Error 1
make[1]: Leaving directory `/opt/kea_hooks'
make: *** [all] Error 2
`
Any idea how I can fix this? We really want to install this on our kea system.

**Comment by Olen** [comment]
Hi,

This hook was written a long time ago, using an early beta-release of kea, so I can not promise that it works with newer releases (it probably won't as the API has changed quite a bit).

But I would _really_ like the hook to be updated, I just don't have any time to do it, and currently no need to, as the kea-server in question is running in a locked down environment with a very special use case, so we have no immediate need to upgrade it.

However, from the error message, it seems like you might just need to add
#include <regex>
in one or more header-files, to at least get it compied.  If it will work when installed is another question...

**Comment by hanserasmus** [comment]
Thanks for the reply. Will rather put this repo on my watchlist to be notifiied when you update it.

**Comment by Olen** [comment]
Hi again.

I am not sure I will update it anytime soon, but please don't hesitate  to fork it and send patches or pull-requests.

**Comment by hanserasmus** [comment]
Hi

So I managed to get this thing compiled on Ubuntu 17.04, and the kea version we are running (1.1.0-1 on Ubuntu) seems not to moan too much about it. But just food for thought:

The regex_replace function was only implemented in g++ 4.9, and the RHEL/Centos distro’s (up to 7.4, at least) only ship with 4.8. While it is possible to make it compile with devtools-4 rhel scl packages, the resulting binary will throw an error “undefined symbol: _ZSt24__throw_out_of_range_fmtPKcz”, which seems to be connected to the version of libstdcpp which ships with RHEL/Centos. Unfortunately, upgrading the standard C++ libraries on a RHEL/Centos machine is not for the faint hearted, and CentOS community will NOT support your questions once you have done this. libstdc++6 and up will not be supported in CentOS7.x. Does the RHEL Boost libraries include a regex replace function? Would it then be possible to use the regex replace function from Boost?

It was just something to think about.

**Comment by Olen** [comment]
Hi again,

Yes, we are running it on Ubuntu, and I did not bother to check other distros.
There are a lot to be done with this hook, but I am glad to hear it still works in kea-1.1.

As I said, I do not have time right now to do any work on it, but I would be extremely happy to accept patches and pull-requests.

I guess there are some glaring issues in the code, which would be obvious to anyone more fluent in c++ than me as well.  I would really like for someone else who finds this useful, to update and extend the hook.
